version: '3.8'

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - VECTOR_DB_URL=http://vectordb:8080
      - MCP_SERVERS=http://mcp-server:3000
    volumes:
      - ./apps/api:/app
      - ./data:/app/data
    depends_on:
      - vectordb
      - mcp-server
    networks:
      - genai-network

  vectordb:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - genai-network

  mcp-server:
    build:
      context: ./mcp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MCP_PORT=3000
    volumes:
      - ./mcp:/app
      - ./data:/app/data
    networks:
      - genai-network

volumes:
  qdrant_storage:

networks:
  genai-network:
    driver: bridge
